# Generated by Django 4.0.3 on 2022-04-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cleantime', models.CharField(choices=[('M', 'Morning'), ('MD', 'Mid-Day'), ('N', 'Night')], default=None, max_length=100)),
            ],
        ),
    ]
